package com.newchinalife;

import com.newchinalife.common.header.in.SysMsgHeader;
import com.newchinalife.service.bd.SrvReqBody;
import com.newchinalife.service.bd.SrvResBody;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Holder;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "PolicyHolderQuerySrvPortType", targetNamespace = "http://www.newchinalife.com")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface PolicyHolderQuerySrvPortType {

	/**
	 * 
	 * @param parametersResBody
	 * @param parametersReqBody
	 * @param parametersReqHeader
	 * @param parametersResHeader
	 */
	@WebMethod(operationName = "PolicyHolderQuery", action = "urn:PolicyHolderQuery")
	public void policyHolderQuery(
            @WebParam(name = "sysHeader", targetNamespace = "http://www.newchinalife.com/common/header/in", header = true, partName = "parametersReqHeader") SysMsgHeader parametersReqHeader,
            @WebParam(name = "request", targetNamespace = "http://www.newchinalife.com/service/bd", partName = "parametersReqBody") SrvReqBody parametersReqBody,
            @WebParam(name = "sysHeader", targetNamespace = "http://www.newchinalife.com/common/header/in", header = true, mode = WebParam.Mode.OUT, partName = "parametersResHeader") Holder<SysMsgHeader> parametersResHeader,
            @WebParam(name = "response", targetNamespace = "http://www.newchinalife.com/service/bd", mode = WebParam.Mode.OUT, partName = "parametersResBody") Holder<SrvResBody> parametersResBody);

}
